name: flutter test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  widget_test:
    name: flutter test
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: subosito/flutter-action@v2
        with:
         channel: 'stable'
      - name: flutter pub get
        run: flutter pub get
      - name: flutter test
        run: flutter test
